apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-sv06
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-sv06
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-sv06
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-sv06
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-sv06
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-twbl-tenant/rhtap-demo-app/hacbs-test-project-sv06@sha256:aef6eccf924c9dc8ce276344f914f142f28b44d7e0a5404fdf264f9c3a332bf7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
